import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import {
  Container,
  WrapContents,
  WrapTitle,
  Title,
  Info,
  WrapButton,
  Button,
} from '../styles/index-style';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>KU:JOIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <WrapContents>
          <WrapTitle>
            <Title>KU:</Title>
            <Title style={{ color: '#2ABF4B' }}>JOIN</Title>
          </WrapTitle>
          <Info>
            KU:JOIN은 중앙 동아리를 알리고 동아리 부원들과 소통하고 다른 동아리
            사람들과 교류할 수 있는 서비스입니다. <br /> <br /> 지금 동아리에
            가입하여 서비스를 즐겨보세요!
          </Info>
          <WrapButton>
            <Button onClick={() => router.push('./signin')}>로그인 하기</Button>
            <Button onClick={() => router.push('./signup')}>
              회원가입 하기
            </Button>
          </WrapButton>
        </WrapContents>
      </Container>

      <footer></footer>
    </div>
  );
};

export default Home;
